//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Core.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonDescriptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonDescriptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Core.Common.CommonDescriptionResource", typeof(CommonDescriptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation type incorrect. Required &quot;{0}&quot;, actual &quot;{1}&quot;..
        /// </summary>
        public static string ActivationByTypeThenByID_IncorrectType {
            get {
                return ResourceManager.GetString("ActivationByTypeThenByID_IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules host &quot;{0}&quot; not found..
        /// </summary>
        public static string ModuleHostNotFoundException_Message {
            get {
                return ResourceManager.GetString("ModuleHostNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &quot;{0}&quot; activation failed..
        /// </summary>
        public static string ServiceActivationException_Message_default {
            get {
                return ResourceManager.GetString("ServiceActivationException_Message_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote activation failed. Types mismatch, required: &quot;{0}&quot;, actual &quot;{1}&quot;..
        /// </summary>
        public static string ServiceActivationException_Message_IncorrectType {
            get {
                return ResourceManager.GetString("ServiceActivationException_Message_IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} location &quot;{0}&quot; not found..
        /// </summary>
        public static string ServiceActivationException_Message_LocationNotFound {
            get {
                return ResourceManager.GetString("ServiceActivationException_Message_LocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason: service is not responding, address: {0}..
        /// </summary>
        public static string ServiceActivationException_Reason_NotAccessable {
            get {
                return ResourceManager.GetString("ServiceActivationException_Reason_NotAccessable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason: instanses mistmatch, url: {0}..
        /// </summary>
        public static string ServiceActivationException_Reason_NotThisServiceInstance {
            get {
                return ResourceManager.GetString("ServiceActivationException_Reason_NotThisServiceInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason: services types mistmatch, url: {0}..
        /// </summary>
        public static string ServiceActivationException_Reason_NotThisServiceType {
            get {
                return ResourceManager.GetString("ServiceActivationException_Reason_NotThisServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service location ambiguous {0}..
        /// </summary>
        public static string ServiceAddressAmbiguouslyException_Message {
            get {
                return ResourceManager.GetString("ServiceAddressAmbiguouslyException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service instanse &quot;{0}&quot; not found..
        /// </summary>
        public static string ServiceInstanceNotFoundException_Message {
            get {
                return ResourceManager.GetString("ServiceInstanceNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &quot;{0}&quot; is already published..
        /// </summary>
        public static string ServicePublishingException_Allready {
            get {
                return ResourceManager.GetString("ServicePublishingException_Allready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &quot;{0}&quot; publication failed..
        /// </summary>
        public static string ServicePublishingException_default {
            get {
                return ResourceManager.GetString("ServicePublishingException_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not implement MarshalByRefObject..
        /// </summary>
        public static string ServicePublishingException_NotMarshalByRef {
            get {
                return ResourceManager.GetString("ServicePublishingException_NotMarshalByRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri &quot;{0}&quot; already in use by service &quot;{1}&quot;..
        /// </summary>
        public static string ServicePublishingException_Uri_Exists {
            get {
                return ResourceManager.GetString("ServicePublishingException_Uri_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher incorrect type..
        /// </summary>
        public static string SevicePublisher_Publish_IncorrectType {
            get {
                return ResourceManager.GetString("SevicePublisher_Publish_IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not edit the built-in groups..
        /// </summary>
        public static string UserManipulationException_BuildInEdit {
            get {
                return ResourceManager.GetString("UserManipulationException_BuildInEdit", resourceCulture);
            }
        }
    }
}
