//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Core.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreConstResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreConstResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Core.Common.CoreConstResource", typeof(CoreConstResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to core_secure_ipc_channel.
        /// </summary>
        internal static string CoreIpcClientChannelName {
            get {
                return ResourceManager.GetString("CoreIpcClientChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to core_secure_tcp_channel.
        /// </summary>
        internal static string CoreTcpClientChannelName {
            get {
                return ResourceManager.GetString("CoreTcpClientChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .coreobj.
        /// </summary>
        internal static string CoreUriPostfix {
            get {
                return ResourceManager.GetString("CoreUriPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CoreUriPrefix {
            get {
                return ResourceManager.GetString("CoreUriPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.sender.
        /// </summary>
        internal static string NotifyEMailSenderSysName {
            get {
                return ResourceManager.GetString("NotifyEMailSenderSysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messanger.sender.
        /// </summary>
        internal static string NotifyMessengerSenderSysName {
            get {
                return ResourceManager.GetString("NotifyMessengerSenderSysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web.sender.
        /// </summary>
        internal static string NotifyWebSenderSysName {
            get {
                return ResourceManager.GetString("NotifyWebSenderSysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.1.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
