//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5403
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Core.Common.Users.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConstResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Core.Common.Users.Resources.ConstResource", typeof(ConstResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddRemoveUser.
        /// </summary>
        internal static string Action_AddRemoveUser_SysName {
            get {
                return ResourceManager.GetString("Action_AddRemoveUser_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1D32DA85-C014-4854-82A1-0F88118BDF94}.
        /// </summary>
        internal static string Action_EditAz_ID {
            get {
                return ResourceManager.GetString("Action_EditAz_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditAz.
        /// </summary>
        internal static string Action_EditAz_SysName {
            get {
                return ResourceManager.GetString("Action_EditAz_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1D4FEEAC-0BF3-4aa9-B096-6D6B104B79B5}.
        /// </summary>
        internal static string Action_EditGroups_ID {
            get {
                return ResourceManager.GetString("Action_EditGroups_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditGroups.
        /// </summary>
        internal static string Action_EditGroups_SysName {
            get {
                return ResourceManager.GetString("Action_EditGroups_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {EF5E6790-F346-4b6e-B662-722BC28CB0DB}.
        /// </summary>
        internal static string Action_EditUser_ID {
            get {
                return ResourceManager.GetString("Action_EditUser_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditUser.
        /// </summary>
        internal static string Action_EditUser_SysName {
            get {
                return ResourceManager.GetString("Action_EditUser_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {B3C5ACA1-8AFD-4bbd-88F8-3FBF838A47C6}.
        /// </summary>
        internal static string AuthCategory_Az_ID {
            get {
                return ResourceManager.GetString("AuthCategory_Az_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.Az.
        /// </summary>
        internal static string AuthCategory_Az_SysName {
            get {
                return ResourceManager.GetString("AuthCategory_Az_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {84C2CED5-0ABB-4e6d-AAE5-F8A346B85C35}.
        /// </summary>
        internal static string AuthCategory_GroupUsers_ID {
            get {
                return ResourceManager.GetString("AuthCategory_GroupUsers_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.GroupUsers.
        /// </summary>
        internal static string AuthCategory_GroupUsers_SysName {
            get {
                return ResourceManager.GetString("AuthCategory_GroupUsers_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {30B85379-3BD8-4d9c-B7FD-CAA86ACEE5C1}.
        /// </summary>
        internal static string Module_ID {
            get {
                return ResourceManager.GetString("Module_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Module_SysName {
            get {
                return ResourceManager.GetString("Module_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {9F34936C-B689-4fc5-B697-7208813EE89B}.
        /// </summary>
        internal static string ModulePart_Common_ID {
            get {
                return ResourceManager.GetString("ModulePart_Common_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to common.
        /// </summary>
        internal static string ModulePart_Common_SysName {
            get {
                return ResourceManager.GetString("ModulePart_Common_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {FEB706B5-3CFB-4589-83C6-EBC8FC56295D}.
        /// </summary>
        internal static string ModulePart_Services_ID {
            get {
                return ResourceManager.GetString("ModulePart_Services_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to common_services.
        /// </summary>
        internal static string ModulePart_Services_SysName {
            get {
                return ResourceManager.GetString("ModulePart_Services_SysName", resourceCulture);
            }
        }
    }
}
