//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5403
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Core.Common.Users.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DescriptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescriptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Core.Common.Users.Resources.DescriptionResource", typeof(DescriptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Action_AddRemoveUser_Description {
            get {
                return ResourceManager.GetString("Action_AddRemoveUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove user..
        /// </summary>
        internal static string Action_AddRemoveUser_Name {
            get {
                return ResourceManager.GetString("Action_AddRemoveUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit permissions and roles.
        /// </summary>
        internal static string Action_EditAz_Description {
            get {
                return ResourceManager.GetString("Action_EditAz_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit permissions.
        /// </summary>
        internal static string Action_EditAz_Name {
            get {
                return ResourceManager.GetString("Action_EditAz_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Action_EditGroups_Description {
            get {
                return ResourceManager.GetString("Action_EditGroups_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit categories and groups.
        /// </summary>
        internal static string Action_EditGroups_Name {
            get {
                return ResourceManager.GetString("Action_EditGroups_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Action_EditUser_Description {
            get {
                return ResourceManager.GetString("Action_EditUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user information.
        /// </summary>
        internal static string Action_EditUser_Name {
            get {
                return ResourceManager.GetString("Action_EditUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting user privileges and roles.
        /// </summary>
        internal static string AuthCategory_Az_Description {
            get {
                return ResourceManager.GetString("AuthCategory_Az_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string AuthCategory_Az_Name {
            get {
                return ResourceManager.GetString("AuthCategory_Az_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users and groups category actions.
        /// </summary>
        internal static string AuthCategory_GroupUsers_Description {
            get {
                return ResourceManager.GetString("AuthCategory_GroupUsers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users and groups.
        /// </summary>
        internal static string AuthCategory_GroupUsers_Name {
            get {
                return ResourceManager.GetString("AuthCategory_GroupUsers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action {0} not found.
        /// </summary>
        internal static string AzActionNotFoundException_Message {
            get {
                return ResourceManager.GetString("AzActionNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category action {0} not found.
        /// </summary>
        internal static string AzCategoryNotFoundException_Message {
            get {
                return ResourceManager.GetString("AzCategoryNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel module provides access to users, groups and permissions..
        /// </summary>
        internal static string Module_Description {
            get {
                return ResourceManager.GetString("Module_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Module_Name {
            get {
                return ResourceManager.GetString("Module_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ModulePart_Common_Description {
            get {
                return ResourceManager.GetString("ModulePart_Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module users common part.
        /// </summary>
        internal static string ModulePart_Common_Name {
            get {
                return ResourceManager.GetString("ModulePart_Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ModulePart_Services_Description {
            get {
                return ResourceManager.GetString("ModulePart_Services_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users service.
        /// </summary>
        internal static string ModulePart_Services_Name {
            get {
                return ResourceManager.GetString("ModulePart_Services_Name", resourceCulture);
            }
        }
    }
}
