//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonDescriptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonDescriptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Common.CommonDescriptionResource", typeof(CommonDescriptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; access denied &quot;{1}&quot;.
        /// </summary>
        internal static string AuthorizingException_Message {
            get {
                return ResourceManager.GetString("AuthorizingException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; access denied &quot;{1}&quot;. Cause: {2}..
        /// </summary>
        internal static string AuthorizingException_MessageEx {
            get {
                return ResourceManager.GetString("AuthorizingException_MessageEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1} access denied {2}..
        /// </summary>
        internal static string AuthorizingException_MessageEx_ReasonFormat_Deny {
            get {
                return ResourceManager.GetString("AuthorizingException_MessageEx_ReasonFormat_Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: access denied..
        /// </summary>
        internal static string AuthorizingException_MessageEx_ReasonFormat_Empty {
            get {
                return ResourceManager.GetString("AuthorizingException_MessageEx_ReasonFormat_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistency a given type instantiation service &quot;{0}&quot; with the facilities infrastructure..
        /// </summary>
        internal static string InstancingTypeMismatchException_Message {
            get {
                return ResourceManager.GetString("InstancingTypeMismatchException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module part &quot;{0}&quot; not found..
        /// </summary>
        internal static string ModulePartNotFoundException_MessageByID {
            get {
                return ResourceManager.GetString("ModulePartNotFoundException_MessageByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service invalid &apos;{0}&apos;. Service must contain attribute ServiceAttribute, implement interfaces IService and IServiceController, have a default constructor..
        /// </summary>
        internal static string ServiceDefinitionException_Message {
            get {
                return ResourceManager.GetString("ServiceDefinitionException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistency a given type of placement service &quot;(0)&quot; with the facilities infrastructure..
        /// </summary>
        internal static string ServiceHostingModelException_Message {
            get {
                return ResourceManager.GetString("ServiceHostingModelException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport type is not defined..
        /// </summary>
        internal static string ServiceInfoBase_TransTypes_ctor_Invalid {
            get {
                return ResourceManager.GetString("ServiceInfoBase_TransTypes_ctor_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to instantiate service &apos;{0}&apos;..
        /// </summary>
        internal static string ServiceInstancingException_Message {
            get {
                return ResourceManager.GetString("ServiceInstancingException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &quot;{0}&quot; not found..
        /// </summary>
        internal static string ServiceNotFoundException_Message {
            get {
                return ResourceManager.GetString("ServiceNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systen name is invalid..
        /// </summary>
        internal static string SysName_ValueInvalid {
            get {
                return ResourceManager.GetString("SysName_ValueInvalid", resourceCulture);
            }
        }
    }
}
