//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonDescriptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonDescriptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Common.CommonDescriptionResource", typeof(CommonDescriptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; access denied &quot;{1}&quot;.
        /// </summary>
        internal static string AuthorizingException_Message {
            get {
                return ResourceManager.GetString("AuthorizingException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; access denied &quot;{1}&quot;. Cause: {2}..
        /// </summary>
        internal static string AuthorizingException_MessageEx {
            get {
                return ResourceManager.GetString("AuthorizingException_MessageEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1} access denied {2}..
        /// </summary>
        internal static string AuthorizingException_MessageEx_ReasonFormat_Deny {
            get {
                return ResourceManager.GetString("AuthorizingException_MessageEx_ReasonFormat_Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: access denied..
        /// </summary>
        internal static string AuthorizingException_MessageEx_ReasonFormat_Empty {
            get {
                return ResourceManager.GetString("AuthorizingException_MessageEx_ReasonFormat_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guest.
        /// </summary>
        internal static string GuestAccountName {
            get {
                return ResourceManager.GetString("GuestAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistency a given type instantiation service &quot;{0}&quot; with the facilities infrastructure..
        /// </summary>
        internal static string InstancingTypeMismatchException_Message {
            get {
                return ResourceManager.GetString("InstancingTypeMismatchException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module &apos;{0}&apos; not found..
        /// </summary>
        internal static string ModuleNotFoundException_MessageByID {
            get {
                return ResourceManager.GetString("ModuleNotFoundException_MessageByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module part &quot;{0}&quot; not found..
        /// </summary>
        internal static string ModulePartNotFoundException_MessageByID {
            get {
                return ResourceManager.GetString("ModulePartNotFoundException_MessageByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service invalid &apos;{0}&apos;. Service must contain attribute ServiceAttribute, implement interfaces IService and IServiceController, have a default constructor..
        /// </summary>
        internal static string ServiceDefinitionException_Message {
            get {
                return ResourceManager.GetString("ServiceDefinitionException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;hostEntry&apos; should contain one address..
        /// </summary>
        internal static string ServiceEndPoint_ctor_argHostEntry_Invalid {
            get {
                return ResourceManager.GetString("ServiceEndPoint_ctor_argHostEntry_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistency a given type of placement service &quot;(0)&quot; with the facilities infrastructure..
        /// </summary>
        internal static string ServiceHostingModelException_Message {
            get {
                return ResourceManager.GetString("ServiceHostingModelException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport type is not defined..
        /// </summary>
        internal static string ServiceInfoBase_TransTypes_ctor_Invalid {
            get {
                return ResourceManager.GetString("ServiceInfoBase_TransTypes_ctor_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to instantiate service &apos;{0}&apos;..
        /// </summary>
        internal static string ServiceInstancingException_Message {
            get {
                return ResourceManager.GetString("ServiceInstancingException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &quot;{0}&quot; not found..
        /// </summary>
        internal static string ServiceNotFoundException_Message {
            get {
                return ResourceManager.GetString("ServiceNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systen name is invalid..
        /// </summary>
        internal static string SysName_ValueInvalid {
            get {
                return ResourceManager.GetString("SysName_ValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System administrator.
        /// </summary>
        internal static string SysRole_Admin_Description {
            get {
                return ResourceManager.GetString("SysRole_Admin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {CD84E66B-B803-40fc-99F9-B2969A54A1DE}.
        /// </summary>
        internal static string SysRole_Admin_ID {
            get {
                return ResourceManager.GetString("SysRole_Admin_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string SysRole_Admin_Name {
            get {
                return ResourceManager.GetString("SysRole_Admin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo user account.
        /// </summary>
        internal static string SysRole_Demo_Description {
            get {
                return ResourceManager.GetString("SysRole_Demo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {64A18D36-7D1B-4509-9616-4C3DBD043DE2}.
        /// </summary>
        internal static string SysRole_Demo_ID {
            get {
                return ResourceManager.GetString("SysRole_Demo_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        internal static string SysRole_Demo_Name {
            get {
                return ResourceManager.GetString("SysRole_Demo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        internal static string SysRole_Everyone_Description {
            get {
                return ResourceManager.GetString("SysRole_Everyone_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {C5CC67D1-C3E8-43c0-A3AD-3928AE3E5B5E}.
        /// </summary>
        internal static string SysRole_Everyone_ID {
            get {
                return ResourceManager.GetString("SysRole_Everyone_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        internal static string SysRole_Everyone_Name {
            get {
                return ResourceManager.GetString("SysRole_Everyone_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member of something.
        /// </summary>
        internal static string SysRole_Member_Description {
            get {
                return ResourceManager.GetString("SysRole_Member_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {BA74CA02-873F-43dc-8470-8620C156BC67}.
        /// </summary>
        internal static string SysRole_Member_ID {
            get {
                return ResourceManager.GetString("SysRole_Member_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string SysRole_Member_Name {
            get {
                return ResourceManager.GetString("SysRole_Member_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object owner.
        /// </summary>
        internal static string SysRole_Owner_Description {
            get {
                return ResourceManager.GetString("SysRole_Owner_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {BBA32183-A14D-48ed-9D39-C6B4D8925FBF}.
        /// </summary>
        internal static string SysRole_Owner_ID {
            get {
                return ResourceManager.GetString("SysRole_Owner_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string SysRole_Owner_Name {
            get {
                return ResourceManager.GetString("SysRole_Owner_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power user.
        /// </summary>
        internal static string SysRole_PowerUser_Description {
            get {
                return ResourceManager.GetString("SysRole_PowerUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {CDDB9E18-6472-4f73-8F4B-2CE273029612}.
        /// </summary>
        internal static string SysRole_PowerUser_ID {
            get {
                return ResourceManager.GetString("SysRole_PowerUser_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power User.
        /// </summary>
        internal static string SysRole_PowerUser_Name {
            get {
                return ResourceManager.GetString("SysRole_PowerUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin of some resource.
        /// </summary>
        internal static string SysRole_ResourceAdmin_Description {
            get {
                return ResourceManager.GetString("SysRole_ResourceAdmin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3011D3B9-2AB0-48df-8B2D-70E6B12BFB6B}.
        /// </summary>
        internal static string SysRole_ResourceAdmin_ID {
            get {
                return ResourceManager.GetString("SysRole_ResourceAdmin_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Admin.
        /// </summary>
        internal static string SysRole_ResourceAdmin_Name {
            get {
                return ResourceManager.GetString("SysRole_ResourceAdmin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        internal static string SysRole_Self_Description {
            get {
                return ResourceManager.GetString("SysRole_Self_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {5D5B7260-F7F7-49f1-A1C9-95FBB6A12604}.
        /// </summary>
        internal static string SysRole_Self_ID {
            get {
                return ResourceManager.GetString("SysRole_Self_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        internal static string SysRole_Self_Name {
            get {
                return ResourceManager.GetString("SysRole_Self_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module service.
        /// </summary>
        internal static string SysRole_Service_Description {
            get {
                return ResourceManager.GetString("SysRole_Service_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0A9EC79B-622F-406f-8F20-92E6B2DEB774}.
        /// </summary>
        internal static string SysRole_Service_ID {
            get {
                return ResourceManager.GetString("SysRole_Service_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string SysRole_Service_Name {
            get {
                return ResourceManager.GetString("SysRole_Service_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User, employee of company.
        /// </summary>
        internal static string SysRole_User_Description {
            get {
                return ResourceManager.GetString("SysRole_User_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ABEF62DB-11A8-4673-9D32-EF1D8AF19DC0}.
        /// </summary>
        internal static string SysRole_User_ID {
            get {
                return ResourceManager.GetString("SysRole_User_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string SysRole_User_Name {
            get {
                return ResourceManager.GetString("SysRole_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        internal static string SysRole_Visitor_Description {
            get {
                return ResourceManager.GetString("SysRole_Visitor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {AAAAF67E-37B9-4e8e-9612-130C1A1CDA64}.
        /// </summary>
        internal static string SysRole_Visitor_ID {
            get {
                return ResourceManager.GetString("SysRole_Visitor_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        internal static string SysRole_Visitor_Name {
            get {
                return ResourceManager.GetString("SysRole_Visitor_Name", resourceCulture);
            }
        }
    }
}
