//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Notify {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Common.Notify.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get tags from formatter of pattern &quot;{0}&quot; failed..
        /// </summary>
        public static string NotifyException_Message_FormatterGetTags {
            get {
                return ResourceManager.GetString("NotifyException_Message_FormatterGetTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not registered sender &quot;{0}&quot;..
        /// </summary>
        public static string NotifyException_Message_NoSenderChannelBySenderName {
            get {
                return ResourceManager.GetString("NotifyException_Message_NoSenderChannelBySenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice hasn&apos;t any senders..
        /// </summary>
        public static string NotifyException_Message_NoSenders {
            get {
                return ResourceManager.GetString("NotifyException_Message_NoSenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For action &quot;{0}&quot; by sender &quot;{1}&quot; no one patterns getted..
        /// </summary>
        public static string NotifyException_Message_NullPatternForSenderName {
            get {
                return ResourceManager.GetString("NotifyException_Message_NullPatternForSenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For pattern &quot;{0}&quot; formatter not instanced..
        /// </summary>
        public static string NotifyException_Message_PatternFormatterNotInstanced {
            get {
                return ResourceManager.GetString("NotifyException_Message_PatternFormatterNotInstanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; not instanced from notify source..
        /// </summary>
        public static string NotifyException_Message_ProviderNotInstanced {
            get {
                return ResourceManager.GetString("NotifyException_Message_ProviderNotInstanced", resourceCulture);
            }
        }
    }
}
