//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Core.Common.Configuration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConstResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Core.Common.Configuration.Resources.ConstResource", typeof(ConstResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {9D75A568-52AA-49d8-AD43-473756CD8903}.
        /// </summary>
        internal static string Action_AuthByLoginPwd_ID {
            get {
                return ResourceManager.GetString("Action_AuthByLoginPwd_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthByLoginPwd.
        /// </summary>
        internal static string Action_AuthByLoginPwd_SysName {
            get {
                return ResourceManager.GetString("Action_AuthByLoginPwd_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1FBB76D4-BA0F-4bed-85A1-5B77C5500E57}.
        /// </summary>
        internal static string Action_AuthSettings_ID {
            get {
                return ResourceManager.GetString("Action_AuthSettings_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthSettings.
        /// </summary>
        internal static string Action_AuthSettings_SysName {
            get {
                return ResourceManager.GetString("Action_AuthSettings_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {9DCA1F0B-3A61-4cae-9234-FBDD06B8B042}.
        /// </summary>
        internal static string Action_Configure_ID {
            get {
                return ResourceManager.GetString("Action_Configure_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string Action_Configure_SysName {
            get {
                return ResourceManager.GetString("Action_Configure_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {FE8E6816-00A8-4705-9EFE-1960ADA2A8D7}.
        /// </summary>
        internal static string Action_CreateSessionTicket_ID {
            get {
                return ResourceManager.GetString("Action_CreateSessionTicket_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateSessionTicket.
        /// </summary>
        internal static string Action_CreateSessionTicket_SysName {
            get {
                return ResourceManager.GetString("Action_CreateSessionTicket_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {B3B961FB-6B00-4ebf-9B9B-DE8182B4B014}.
        /// </summary>
        internal static string AuthCategory_Authentication_ID {
            get {
                return ResourceManager.GetString("AuthCategory_Authentication_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.Authentication.
        /// </summary>
        internal static string AuthCategory_Authentication_SysName {
            get {
                return ResourceManager.GetString("AuthCategory_Authentication_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {287F38ED-FFA9-4c52-9A2D-C39E58855660}.
        /// </summary>
        internal static string AuthCategory_Configure_ID {
            get {
                return ResourceManager.GetString("AuthCategory_Configure_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.Configuration.
        /// </summary>
        internal static string AuthCategory_Configure_SysName {
            get {
                return ResourceManager.GetString("AuthCategory_Configure_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {EF2B5BC1-F27F-4f75-9493-3B307ABC49B9}.
        /// </summary>
        internal static string Module_ID {
            get {
                return ResourceManager.GetString("Module_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Module_SysName {
            get {
                return ResourceManager.GetString("Module_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {F30E4962-5938-425b-B4FD-25A5F09FDB2C}.
        /// </summary>
        internal static string ModulePart_Common_ID {
            get {
                return ResourceManager.GetString("ModulePart_Common_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to common.
        /// </summary>
        internal static string ModulePart_Common_SysName {
            get {
                return ResourceManager.GetString("ModulePart_Common_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {AE25BEB1-5850-4eb0-AD69-8EB93069F657}.
        /// </summary>
        internal static string ModulePart_HostServices_ID {
            get {
                return ResourceManager.GetString("ModulePart_HostServices_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to host_services.
        /// </summary>
        internal static string ModulePart_HostServices_SysName {
            get {
                return ResourceManager.GetString("ModulePart_HostServices_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {70F57692-5240-424c-9930-279F8C4D774C}.
        /// </summary>
        internal static string ModulePart_Services_ID {
            get {
                return ResourceManager.GetString("ModulePart_Services_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to common_services.
        /// </summary>
        internal static string ModulePart_Services_SysName {
            get {
                return ResourceManager.GetString("ModulePart_Services_SysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {005E6280-3852-403c-A768-8AF42A059269}.
        /// </summary>
        internal static string ServiceID_Authentication {
            get {
                return ResourceManager.GetString("ServiceID_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {37017EA8-7826-43b6-BDF3-D5A02AE80C69}.
        /// </summary>
        internal static string ServiceID_Configuration {
            get {
                return ResourceManager.GetString("ServiceID_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {FA551358-03F9-4e8d-B807-3E8186BE0CD9}.
        /// </summary>
        internal static string ServiceID_ModuleHosting {
            get {
                return ResourceManager.GetString("ServiceID_ModuleHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {A4F5E7CC-F489-4be7-B4CC-2602B45C92D0}.
        /// </summary>
        internal static string ServiceID_ModuleInformation {
            get {
                return ResourceManager.GetString("ServiceID_ModuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {47E82D68-7D20-4fb3-8459-5B8F765EA7AF}.
        /// </summary>
        internal static string ServiceID_Notify {
            get {
                return ResourceManager.GetString("ServiceID_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {C96B5317-B883-4366-8A2D-E0A2D094DC2F}.
        /// </summary>
        internal static string ServiceID_SecureAuthentication {
            get {
                return ResourceManager.GetString("ServiceID_SecureAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {AC9037AE-800F-4fc9-841A-D5179A351701}.
        /// </summary>
        internal static string ServiceID_ServiceLocator {
            get {
                return ResourceManager.GetString("ServiceID_ServiceLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string ServiceSysName_Authentication {
            get {
                return ResourceManager.GetString("ServiceSysName_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CacheInfoStorage.
        /// </summary>
        internal static string ServiceSysName_CacheInfoStorage {
            get {
                return ResourceManager.GetString("ServiceSysName_CacheInfoStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ServiceSysName_Configuration {
            get {
                return ResourceManager.GetString("ServiceSysName_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module_hosting.
        /// </summary>
        internal static string ServiceSysName_ModuleHosting {
            get {
                return ResourceManager.GetString("ServiceSysName_ModuleHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleInformation.
        /// </summary>
        internal static string ServiceSysName_ModuleInformation {
            get {
                return ResourceManager.GetString("ServiceSysName_ModuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        internal static string ServiceSysName_Notify {
            get {
                return ResourceManager.GetString("ServiceSysName_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureAuthentication.
        /// </summary>
        internal static string ServiceSysName_SecureAuthentication {
            get {
                return ResourceManager.GetString("ServiceSysName_SecureAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceLocator.
        /// </summary>
        internal static string ServiceSysName_ServiceLocator {
            get {
                return ResourceManager.GetString("ServiceSysName_ServiceLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemConfiguration.
        /// </summary>
        internal static string ServiceSysName_SysCfg {
            get {
                return ResourceManager.GetString("ServiceSysName_SysCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {A37EE56E-3302-4a7b-B67E-DDBEA64CD032}.
        /// </summary>
        internal static string SysAccount_CoreSystem_ID {
            get {
                return ResourceManager.GetString("SysAccount_CoreSystem_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {712D9EC3-5D2B-4b13-824F-71F00191DCCA}.
        /// </summary>
        internal static string SysAccount_Guest_ID {
            get {
                return ResourceManager.GetString("SysAccount_Guest_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {32DD8994-68C8-420e-A705-C354482160A5}.
        /// </summary>
        internal static string SysAccount_System_ID {
            get {
                return ResourceManager.GetString("SysAccount_System_ID", resourceCulture);
            }
        }
    }
}
