//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Core.Common.Configuration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DescriptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescriptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Core.Common.Configuration.Resources.DescriptionResource", typeof(DescriptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Action_AuthByLoginPwd_Description {
            get {
                return ResourceManager.GetString("Action_AuthByLoginPwd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login/Password authentication.
        /// </summary>
        internal static string Action_AuthByLoginPwd_Name {
            get {
                return ResourceManager.GetString("Action_AuthByLoginPwd_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changing, settings.
        /// </summary>
        internal static string Action_AuthSettings_Description {
            get {
                return ResourceManager.GetString("Action_AuthSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication settings.
        /// </summary>
        internal static string Action_AuthSettings_Name {
            get {
                return ResourceManager.GetString("Action_AuthSettings_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Action_Configure_Description {
            get {
                return ResourceManager.GetString("Action_Configure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System configure.
        /// </summary>
        internal static string Action_Configure_Name {
            get {
                return ResourceManager.GetString("Action_Configure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Action_CreateSessionTicket_Description {
            get {
                return ResourceManager.GetString("Action_CreateSessionTicket_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session ticket authentication.
        /// </summary>
        internal static string Action_CreateSessionTicket_Name {
            get {
                return ResourceManager.GetString("Action_CreateSessionTicket_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string AuthCategory_Authentication_Description {
            get {
                return ResourceManager.GetString("AuthCategory_Authentication_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string AuthCategory_Authentication_Name {
            get {
                return ResourceManager.GetString("AuthCategory_Authentication_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthCategory_Configure_Description {
            get {
                return ResourceManager.GetString("AuthCategory_Configure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string AuthCategory_Configure_Name {
            get {
                return ResourceManager.GetString("AuthCategory_Configure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main core module..
        /// </summary>
        internal static string Module_Description {
            get {
                return ResourceManager.GetString("Module_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Module_Name {
            get {
                return ResourceManager.GetString("Module_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ModulePart_Common_Description {
            get {
                return ResourceManager.GetString("ModulePart_Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration module common part.
        /// </summary>
        internal static string ModulePart_Common_Name {
            get {
                return ResourceManager.GetString("ModulePart_Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ModulePart_HostServices_Description {
            get {
                return ResourceManager.GetString("ModulePart_HostServices_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module configuration services.
        /// </summary>
        internal static string ModulePart_HostServices_Name {
            get {
                return ResourceManager.GetString("ModulePart_HostServices_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ModulePart_Services_Description {
            get {
                return ResourceManager.GetString("ModulePart_Services_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module configuration services.
        /// </summary>
        internal static string ModulePart_Services_Name {
            get {
                return ResourceManager.GetString("ModulePart_Services_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication service.
        /// </summary>
        internal static string ServiceDescription_Authentication {
            get {
                return ResourceManager.GetString("ServiceDescription_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache service.
        /// </summary>
        internal static string ServiceDescription_CacheInfoStorage {
            get {
                return ResourceManager.GetString("ServiceDescription_CacheInfoStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration service.
        /// </summary>
        internal static string ServiceDescription_Configuration {
            get {
                return ResourceManager.GetString("ServiceDescription_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage and configure hosts for service parts modules.
        /// </summary>
        internal static string ServiceDescription_ModuleHosting {
            get {
                return ResourceManager.GetString("ServiceDescription_ModuleHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ervice definition information on the modules of their parts and services.
        /// </summary>
        internal static string ServiceDescription_ModuleInformation {
            get {
                return ResourceManager.GetString("ServiceDescription_ModuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert service.
        /// </summary>
        internal static string ServiceDescription_Notify {
            get {
                return ResourceManager.GetString("ServiceDescription_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure authentication service.
        /// </summary>
        internal static string ServiceDescription_SecureAuthentication {
            get {
                return ResourceManager.GetString("ServiceDescription_SecureAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location service.
        /// </summary>
        internal static string ServiceDescription_ServiceLocator {
            get {
                return ResourceManager.GetString("ServiceDescription_ServiceLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System configuration service.
        /// </summary>
        internal static string ServiceDescription_SysCfg {
            get {
                return ResourceManager.GetString("ServiceDescription_SysCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string ServiceName_Authentication {
            get {
                return ResourceManager.GetString("ServiceName_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache storage.
        /// </summary>
        internal static string ServiceName_CacheInfoStorage {
            get {
                return ResourceManager.GetString("ServiceName_CacheInfoStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ServiceName_Configuration {
            get {
                return ResourceManager.GetString("ServiceName_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostingControl.
        /// </summary>
        internal static string ServiceName_ModuleHosting {
            get {
                return ResourceManager.GetString("ServiceName_ModuleHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleDescriber.
        /// </summary>
        internal static string ServiceName_ModuleInformation {
            get {
                return ResourceManager.GetString("ServiceName_ModuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        internal static string ServiceName_Notify {
            get {
                return ResourceManager.GetString("ServiceName_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureAuthentication.
        /// </summary>
        internal static string ServiceName_SecureAuthentication {
            get {
                return ResourceManager.GetString("ServiceName_SecureAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceLocator.
        /// </summary>
        internal static string ServiceName_ServiceLocator {
            get {
                return ResourceManager.GetString("ServiceName_ServiceLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemConfiguration.
        /// </summary>
        internal static string ServiceName_SysCfg {
            get {
                return ResourceManager.GetString("ServiceName_SysCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host {0} is not included in the trusted zone.
        /// </summary>
        internal static string ServiceRegistrationException_Message {
            get {
                return ResourceManager.GetString("ServiceRegistrationException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asc system.
        /// </summary>
        internal static string SysAccount_CoreSystem_Name {
            get {
                return ResourceManager.GetString("SysAccount_CoreSystem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guest.
        /// </summary>
        internal static string SysAccount_Guest_Name {
            get {
                return ResourceManager.GetString("SysAccount_Guest_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module-host.
        /// </summary>
        internal static string SysAccount_ModuleHost_Name {
            get {
                return ResourceManager.GetString("SysAccount_ModuleHost_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service-host.
        /// </summary>
        internal static string SysAccount_ServiceHost_Name {
            get {
                return ResourceManager.GetString("SysAccount_ServiceHost_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.
        /// </summary>
        internal static string SysAccount_System_Name {
            get {
                return ResourceManager.GetString("SysAccount_System_Name", resourceCulture);
            }
        }
    }
}
